# Generated by Django 3.0.5 on 2022-03-07 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('income', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(75000)])),
                ('gender', models.CharField(max_length=1)),
                ('MARITAL_STATUS', models.CharField(max_length=6)),
                ('loan_type', models.CharField(default='Home_loan', max_length=13)),
            ],
        ),
    ]
