# Generated by Django 3.0.5 on 2022-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_homeloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='homeloan',
        ),
    ]
