# Generated by Django 3.0.7 on 2022-02-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20220223_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='sum_assurance',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='tenure',
        ),
    ]
