# Generated by Django 3.0.7 on 2022-02-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20220224_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='Loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.Loan'),
        ),
    ]
