# Generated by Django 3.0.7 on 2022-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='homeloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(max_length=10000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], max_length=1)),
                ('MARITAL_STATUS', models.CharField(choices=[('select', 'Select'), ('y', 'Yes'), ('n', 'No')], default='select', max_length=6)),
                ('loan_type', models.CharField(choices=[('Home_loan', 'Home Loan'), ('Car_loan', 'Car Loan'), ('Personal_loan', 'Personal Loan')], default='Home_loan', max_length=13)),
            ],
        ),
    ]
