# Generated by Django 3.0.7 on 2022-02-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_contact_homeloan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeloan',
            name='income',
        ),
    ]
