# Generated by Django 3.0.7 on 2022-02-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_homeloan_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeloan',
            name='email',
            field=models.EmailField(default='kevin', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeloan',
            name='firstname',
            field=models.CharField(default='kevin', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeloan',
            name='lastname',
            field=models.CharField(default='kevin', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeloan',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
