# Generated by Django 3.0.7 on 2022-02-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20220209_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeloan',
            name='income',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
