# Generated by Django 3.0.7 on 2022-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_homeloan_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeloan',
            name='aadhar',
            field=models.ImageField(default='kevin', max_length=13, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='MARITAL_STATUS',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='loan_type',
            field=models.CharField(default='Home_loan', max_length=13),
        ),
    ]
