# Generated by Django 3.0.7 on 2022-02-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20220210_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeloan',
            old_name='aadhar',
            new_name='file',
        ),
    ]
