# Generated by Django 3.0.7 on 2022-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20220210_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeloan',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='image_upload_to'),
        ),
    ]
