# Generated by Django 3.0.7 on 2022-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20220210_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeloan',
            name='file',
            field=models.ImageField(default='kevin', upload_to='home/kevin/Desktop/sem8/Django-LMS-Project-master/images/upload'),
            preserve_default=False,
        ),
    ]
