# Generated by Django 3.0.7 on 2022-02-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20220210_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeloan',
            name='file',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
