# Generated by Django 3.0.7 on 2022-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20220210_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeloan',
            name='file',
            field=models.ImageField(upload_to='static/images/%Y/%m/%D'),
        ),
    ]
