# Generated by Django 3.0.7 on 2022-02-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_auto_20220210_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeloan',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
