# Generated by Django 3.0.7 on 2022-02-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_auto_20220211_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeloan',
            name='file',
        ),
    ]
