# Generated by Django 3.0.7 on 2022-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_remove_homeloan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeloan',
            name='file',
            field=models.FileField(default='kevin', upload_to=''),
            preserve_default=False,
        ),
    ]
