# Generated by Django 3.0.7 on 2022-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_remove_homeloan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeloan',
            name='income',
            field=models.IntegerField(blank=True, max_length=12),
        ),
    ]
