# Generated by Django 4.0.2 on 2022-02-19 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_personalloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carloan',
            name='income',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(25000)]),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='income',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(75000)]),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='income',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(20000)]),
        ),
    ]
